on:
  workflow_dispatch:

jobs:
  dotnet_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8
      - uses: docker/setup-buildx-action@v3
      - run: cd server-app && cd tests && dotnet test